name: 'Validate Helm Chart'
description: 'Validates a helm chart using helm lint, and helm template commands. Optionally validates that the only branch merged into main is alpha'
inputs:
  validate-main-alpha-merge:
    description: 'When true, the action will fail if the pull request is into the `main` branch and the source branch is not `alpha`'
    required: false
    default: true
  lint-args:
    description: 'Args to pass to the lint command. i.e. `--set x=y`'
    required: false
    default: ''
  template-args:
    description: 'Args to pass to the template command. i.e. `--set x=y`'
    required: false
    default: ''
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.2
    - name: Lint and Template chart
      shell: bash
      run: |
        helm dependency update chart
        helm lint chart ${{ inputs.lint-args }}
        helm template chart ${{ inputs.template-args }}
    - name: Validate branch
      if: inputs.validate-main-alpha-merge && github.base_ref == 'main' && github.head_ref != 'alpha'
      shell: bash
      run: |
        echo "Branch ${{ github.head_ref }} is not allowed to be merged to main. Only alpha is allowed to be merged to main."
        exit 1